name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    env:
      CI: true

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: nuxt/actions-yarn@master
        with: 
          node-version: 12
      - run: yarn install
      - run: yarn build
      - run: yarn test --passWithNoTests
